name: language_learner_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  firebase_core: ^ 3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0
  chewie: ^1.4.0  # Optional for better video controls
  video_player: ^2.5.1
  youtube_player_flutter: ^8.0.0 # Optional if you want to use a YouTube-specific player
  webview_flutter: ^4.0.0
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1 # For Facebook, if needed
  google_sign_in_web: ^0.12.4+3
  googleapis: ^13.2.0 # to interact with Google Forms, if needed
  http: ^1.2.2 # to submit form data to Google Forms (Optional)
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  url_launcher: ^6.0.20 # Use the latest version
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

